<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSFz6ZPL\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSFz6ZPL/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSFz6ZPL.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSFz6ZPL\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerSFz6ZPL\App_KernelDevDebugContainer([
    'container.build_hash' => 'SFz6ZPL',
    'container.build_id' => '6b87e844',
    'container.build_time' => 1668382125,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSFz6ZPL');
