<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container4tT6JMT\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container4tT6JMT/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container4tT6JMT.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container4tT6JMT\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container4tT6JMT\App_KernelDevDebugContainer([
    'container.build_hash' => '4tT6JMT',
    'container.build_id' => '790654b8',
    'container.build_time' => 1668120140,
], __DIR__.\DIRECTORY_SEPARATOR.'Container4tT6JMT');
