<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGxv2vWY\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGxv2vWY/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGxv2vWY.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGxv2vWY\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerGxv2vWY\App_KernelDevDebugContainer([
    'container.build_hash' => 'Gxv2vWY',
    'container.build_id' => 'd5fc4e8d',
    'container.build_time' => 1668372817,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGxv2vWY');
